/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamResolution;
import com.sun.javafx.application.PlatformImpl;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.collections.ObservableList;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface;

/**
 *
 * @author DuongPC
 */
public class FrmMain extends javax.swing.JFrame {

    // Create a media player factory
    private MediaPlayerFactory mediaPlayerFactory;

    // Create a new media player instance for the run-time platform
    private EmbeddedMediaPlayer mediaPlayer;

    public static int isRuningWeb;

    public static final JFrame frameVidWeb = new JFrame();
    ;

    Webcam webCam;
    Boolean isRunningCam = false;
    Boolean isRunningVideo = false;

    String url = "";

    /**
     * Creates new form frmMain
     */
    public FrmMain() {
        initComponents();

        isRuningWeb = 0;

        // Create a media player for Video File:
        mediaPlayerFactory = new MediaPlayerFactory();
        mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();
        CanvasVideoSurface videoSurface = mediaPlayerFactory.newVideoSurface(canvas_playVideo);
        mediaPlayer.setVideoSurface(videoSurface);
        //

        // Create panel for Camera
        webCam = Webcam.getDefault();
        webCam.setViewSize(WebcamResolution.VGA.getSize());
        //

        jPanel_main.revalidate();
        jPanel_main.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_main = new javax.swing.JPanel();
        jPanel_control = new javax.swing.JPanel();
        jPanel_button = new javax.swing.JPanel();
        jButton_chooseFile = new javax.swing.JButton();
        jButton_camera = new javax.swing.JButton();
        jButton_website = new javax.swing.JButton();
        jPanel_textMessage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_displayMessage = new javax.swing.JTextArea();
        jTextField_typeMessage = new javax.swing.JTextField();
        jButton_sendMessage = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel_displayVideoFile = new javax.swing.JPanel();
        canvas_playVideo = new java.awt.Canvas();
        jLabel_displayCamera = new javax.swing.JLabel();
        jPanel_displayWebsite = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N

        jButton_chooseFile.setText("CHOOSE FILE");
        jButton_chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chooseFileActionPerformed(evt);
            }
        });

        jButton_camera.setText("CAMERA");
        jButton_camera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cameraActionPerformed(evt);
            }
        });

        jButton_website.setText("YOUTUBE");
        jButton_website.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_websiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buttonLayout = new javax.swing.GroupLayout(jPanel_button);
        jPanel_button.setLayout(jPanel_buttonLayout);
        jPanel_buttonLayout.setHorizontalGroup(
            jPanel_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_chooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_camera, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_website, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_buttonLayout.setVerticalGroup(
            jPanel_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_camera, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton_website, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_chooseFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea_displayMessage.setColumns(20);
        jTextArea_displayMessage.setRows(5);
        jScrollPane2.setViewportView(jTextArea_displayMessage);

        jTextField_typeMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_typeMessageKeyPressed(evt);
            }
        });

        jButton_sendMessage.setText("SEND");
        jButton_sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sendMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_textMessageLayout = new javax.swing.GroupLayout(jPanel_textMessage);
        jPanel_textMessage.setLayout(jPanel_textMessageLayout);
        jPanel_textMessageLayout.setHorizontalGroup(
            jPanel_textMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_textMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_textMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel_textMessageLayout.createSequentialGroup()
                        .addComponent(jTextField_typeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_textMessageLayout.setVerticalGroup(
            jPanel_textMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_textMessageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_textMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_typeMessage)
                    .addComponent(jButton_sendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_controlLayout = new javax.swing.GroupLayout(jPanel_control);
        jPanel_control.setLayout(jPanel_controlLayout);
        jPanel_controlLayout.setHorizontalGroup(
            jPanel_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_textMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_controlLayout.setVerticalGroup(
            jPanel_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_controlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_textMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel_displayVideoFile.setPreferredSize(new java.awt.Dimension(635, 480));

        canvas_playVideo.setBackground(new java.awt.Color(0, 0, 0));
        canvas_playVideo.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout jPanel_displayVideoFileLayout = new javax.swing.GroupLayout(jPanel_displayVideoFile);
        jPanel_displayVideoFile.setLayout(jPanel_displayVideoFileLayout);
        jPanel_displayVideoFileLayout.setHorizontalGroup(
            jPanel_displayVideoFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas_playVideo, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        jPanel_displayVideoFileLayout.setVerticalGroup(
            jPanel_displayVideoFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_displayVideoFileLayout.createSequentialGroup()
                .addComponent(canvas_playVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Video File", jPanel_displayVideoFile);
        jTabbedPane.addTab("Camera", jLabel_displayCamera);

        jPanel_displayWebsite.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel_displayWebsiteLayout = new javax.swing.GroupLayout(jPanel_displayWebsite);
        jPanel_displayWebsite.setLayout(jPanel_displayWebsiteLayout);
        jPanel_displayWebsiteLayout.setHorizontalGroup(
            jPanel_displayWebsiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        jPanel_displayWebsiteLayout.setVerticalGroup(
            jPanel_displayWebsiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Website", jPanel_displayWebsite);

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane)
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("jTabbedPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chooseFileActionPerformed
        // TODO add your handling code here:
        if (isRunningCam) {
            webCam.close();
            isRunningCam = false;
        }

        jTabbedPane.setSelectedIndex(0);

        if (!isRunningVideo) {
            isRunningVideo = true;
            
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showOpenDialog(jPanel_main);
            File file = fileChooser.getSelectedFile();
            url = file.getPath();
            System.out.println(url);
            jTextArea_displayMessage.setText("check text\n");
            jTextArea_displayMessage.append(url + "\n");
            mediaPlayer.playMedia(url);
        }
    }//GEN-LAST:event_jButton_chooseFileActionPerformed

    private void jButton_sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendMessageActionPerformed
        // TODO add your handling code here:
        Sentencefromserver.sendingSentence = jTextField_typeMessage.getText();
        jTextField_typeMessage.setText(null);
        jTextArea_displayMessage.append("From Myself: " + Sentencefromserver.sendingSentence + "\n");
        jPanel_control.revalidate();
        jPanel_control.repaint();
    }//GEN-LAST:event_jButton_sendMessageActionPerformed

    private void jTextField_typeMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_typeMessageKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Sentencefromserver.sendingSentence = jTextField_typeMessage.getText();
            jTextField_typeMessage.setText(null);
            jTextArea_displayMessage.append("From Myself: " + Sentencefromserver.sendingSentence + "\n");
            jPanel_control.revalidate();
            jPanel_control.repaint();
        }
    }//GEN-LAST:event_jTextField_typeMessageKeyPressed

    private void jButton_cameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cameraActionPerformed
        // TODO add your handling code here:
        if (isRunningVideo) {
            mediaPlayer.pause();
            isRunningVideo = false;
        }
        
        jTabbedPane.setSelectedIndex(1);

        if (!isRunningCam) {
            isRunningCam = true;
            webCam.open();
            new VideoFeedTaker().start();
        }
    }//GEN-LAST:event_jButton_cameraActionPerformed

    private void jButton_websiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_websiteActionPerformed
        // TODO add your handling code here:
        if (isRunningCam) {
            webCam.close();
            isRunningCam = false;
        }
        if (isRunningVideo) {
            mediaPlayer.pause();
            isRunningVideo = false;
        }

        jTabbedPane.setSelectedIndex(2);

        isRuningWeb = 1;

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                frameVidWeb.add(new JpWebsiteVideo());

                frameVidWeb.setMinimumSize(new Dimension(825, 595));
                frameVidWeb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frameVidWeb.setLocationRelativeTo(null);
                frameVidWeb.setVisible(true);
            }
        });

    }//GEN-LAST:event_jButton_websiteActionPerformed

    class VideoFeedTaker extends Thread {

        @Override
        public void run() {
            while (isRunningCam) {
                try {
                    Image image = webCam.getImage();
                    jLabel_displayCamera.setIcon(new ImageIcon(image));
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas_playVideo;
    private javax.swing.JButton jButton_camera;
    private javax.swing.JButton jButton_chooseFile;
    private javax.swing.JButton jButton_sendMessage;
    private javax.swing.JButton jButton_website;
    private javax.swing.JLabel jLabel_displayCamera;
    private javax.swing.JPanel jPanel_button;
    private javax.swing.JPanel jPanel_control;
    private javax.swing.JPanel jPanel_displayVideoFile;
    private javax.swing.JPanel jPanel_displayWebsite;
    public static javax.swing.JPanel jPanel_main;
    public static javax.swing.JPanel jPanel_textMessage;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    public static javax.swing.JTextArea jTextArea_displayMessage;
    public static javax.swing.JTextField jTextField_typeMessage;
    // End of variables declaration//GEN-END:variables
}
